destination: ../build
site: boilerpate - resume
name: Ilona Iliza Ray
email: ilonailizaray@gmail.com
description: personal resume
baseurl: ""
url: "http://ilonaray.github.io/"



# Build settings
markdown: kramdown

prose:
    siteurl: "http://ilonaray.github.io/"
    ignore:
        - index.html
        - CNAME
        - _config.yml
        - README.md
        - se
        - img
        - css
        - brev
        - _sass
        - _layouts
        - _includes
        - .sass-cache
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "title"

company: wimse
company_desc: wimse är en komplett och kreativ webbbyrå belägen i göteborg. Vi hjälper företag till ökad lönsamhet genom att förbättra och utveckla afärsmodeller. Genom kreativt tänkande, nyskapande idéer och med tekniskt lösningar kan vi tillsammans förbättra din verksamhet. Vi skapar plattformat som tilltalar och stärker din profilering och närvaro på Internet.
company_url: http://wimse.se
